### ISSUE TITLE
Install instructions in README fail on Windows 11 

### ISSUE THREAD

**Issue by Walms** [yakGPT/yakGPT#1]
This tool looks amazing, thanks for all the work you've put in. Just to let you know the install instructions might be failing for some people. I suspect it's just that I don't have the dependencies setup for my machine. I don't know much about yarn / npm as it's not an ecosystem I work with so I haven't attempted to debug. 

Yarn works. 

yarn build results in:

```

info  - Collecting page data
info  - Creating an optimized production build ...TypeError: Cannot read properties of null (reading 'useRef')
    at exports.useRef (C:\...\yakGPT\node_modules\react\cjs\react.production.min.js:25:337)
```
```
> Build error occurred
Error: Export encountered errors on following paths:
        /
        /_error: /404
        /_error: /500
    at c:\...\yakGPT\node_modules\next\dist\export\index.js:425:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (c:\...\yakGPT\node_modules\next\dist\trace\trace.js:79:20)
    at async c:\...\yakGPT\node_modules\next\dist\build\index.js:1422:21
    at async Span.traceAsyncFn (c:\...\yakGPT\node_modules\next\dist\trace\trace.js:79:20)
    at async c:\...\yakGPT\node_modules\next\dist\build\index.js:1280:17
    at async Span.traceAsyncFn (c:\...\yakGPT\node_modules\next\dist\trace\trace.js:79:20)
    at async Object.build [as default] (c:\...\yakGPT\node_modules\next\dist\build\index.js:73:29)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by yakGPT** [comment]
Hey @Walms, thanks for the kind words. Does the docker image that was just contributed in README work for you?

**Comment by yakGPT** [comment]
Closing for now ^_^
